# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
    files: ^src/
  - id: end-of-file-fixer
    files: ^src/
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    files: ^src/
# - repo: https://github.com/regebro/pyroma
#   rev: "4.2"
#   hooks:
#   - id: pyroma
#     exclude: ^examples/
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.1
  hooks:
    - id: pyupgrade
      args: ["--py37-plus"]
      exclude: ^examples/